### ISSUE TITLE
DateIntervalFilter: Possible logical error with from to current time instead of 00:00:00 - 23:59:59

### ISSUE THREAD

**Issue by mauthi** [enso-ui/filters#2]
This is  a **bug or feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
(enso is made of many specialized packages: https://github.com/laravel-enso)
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

If I use e.g. today I would await results from today 00:00:00 to today 23:59:59.
You are using results from today with current time to tomorrow with current time.

Same for yesterday, ...

**Comment by aocneanu** [comment]
Is this a table issue or a date interval filter one?

**Comment by mauthi** [comment]
I guess it's a date interval filter one because min and max date are build here:
https://github.com/enso-ui/filters/blob/master/src/renderless/CoreDateFilter.vue

e.g. today
```
        today() {
            this.interval.min = format(new Date(), this.alternateFormat);
            this.interval.max = format(addDays(new Date(), 1), this.alternateFormat);
        },
```

**Comment by aocneanu** [comment]
It shouldn't be a problem here..

Check in your vue console the values for min/max

**Comment by mauthi** [comment]
I checked that again and now it's ok - I think that was a problem in combination with dbDateFormat or something else. So the time issue is closed.

But - there is another problem.
If I filter for e.g. today I get the following query
```
where
  `cash_book_entries`.`entry_date` >= "2019-07-17"
  and `cash_book_entries`.`entry_date` <= "2019-07-18"
```
- Result: I get entries for today and tomorrow.
- I think that replacing `this.interval.max = format(addDays(new Date(), 1), this.alternateFormat);` with `this.interval.max = this.interval.min;` would solve the problem
- same for yesterday
- sevenDays and thirtyDays are both including tomorrow to result which I think is also not correct
